version: '3.8'
services:
  app:
    environment:
      - ENV_TYPE=docker
    build: . # build the image from the Dockerfile in the current directory
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

