version: '3.8'
services:
  app:
    environment:
      - ENV_TYPE=docker
    build: . # build the image from the Dockerfile in the current directory
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo: #<- this is the host name when running in docker!
    image: bradleydean/basic-mongo-v0.0
    ports:
      - "27017:27017"
    # volumes:
      # - ./init-scripts/mongo-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

