version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.11.0
      - image: bradleydean/basic-mongo-v0.0
        environment:
          MONGO_INITDB_DATABASE: myAppDb

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Compile TypeScript
          command: npm run compile-ts
      - run:
          name: Wait for MongoDB to be ready
          command: |
            echo "Waiting for MongoDB to start..."
            while ! nc -z localhost 27017; do
              sleep 1
            done
            echo "MongoDB started"
      - run:
          name: Run Unit Tests
          command: npm run test:unit
      - run:
          name: Run Integration Tests
          command: npm run test:integration
      - run:
          name: Start Server and Test
          command: |
            npm start &
            sleep 5
            curl --fail http://localhost:3000/
    

workflows:
  version: 2
  build:
    jobs:
      - build-and-test